python runner.py configs/oct-multi-ant.json max_visible_time
python runner.py configs/oct-multi-ant.json max_matching
python runner.py configs/oct-multi-ant.json min_distance
python runner.py configs/oct-multi-ant.json gs_state_aware_matching
python runner.py configs/jan-multi-ant.json max_visible_time
python runner.py configs/jan-multi-ant.json max_matching
python runner.py configs/jan-multi-ant.json min_distance
python runner.py configs/jan-multi-ant.json gs_state_aware_matching
python runner.py configs/apr-multi-ant.json max_visible_time
python runner.py configs/apr-multi-ant.json max_matching
python runner.py configs/apr-multi-ant.json min_distance
python runner.py configs/apr-multi-ant.json gs_state_aware_matching
python runner.py configs/jul-multi-ant.json max_visible_time
python runner.py configs/jul-multi-ant.json max_matching
python runner.py configs/jul-multi-ant.json min_distance
python runner.py configs/jul-multi-ant.json gs_state_aware_matching