python runner.py configs/oct-silk.json max_visible_time
python runner.py configs/oct-silk.json max_matching
python runner.py configs/oct-silk.json min_distance
python runner.py configs/oct-silk.json gs_state_aware_matching
python runner.py configs/jan-silk.json max_visible_time
python runner.py configs/jan-silk.json max_matching
python runner.py configs/jan-silk.json min_distance
python runner.py configs/jan-silk.json gs_state_aware_matching
python runner.py configs/apr-silk.json max_visible_time
python runner.py configs/apr-silk.json max_matching
python runner.py configs/apr-silk.json min_distance
python runner.py configs/apr-silk.json gs_state_aware_matching
python runner.py configs/jul-silk.json max_visible_time
python runner.py configs/jul-silk.json max_matching
python runner.py configs/jul-silk.json min_distance
python runner.py configs/jul-silk.json gs_state_aware_matching