python runner.py configs/oct.json max_visible_time
python runner.py configs/oct.json max_matching
python runner.py configs/oct.json min_distance
python runner.py configs/oct.json gs_state_aware_matching
python runner.py configs/jan.json max_visible_time
python runner.py configs/jan.json max_matching
python runner.py configs/jan.json min_distance
python runner.py configs/jan.json gs_state_aware_matching
python runner.py configs/apr.json max_visible_time
python runner.py configs/apr.json max_matching
python runner.py configs/apr.json min_distance
python runner.py configs/apr.json gs_state_aware_matching
python runner.py configs/jul.json max_visible_time
python runner.py configs/jul.json max_matching
python runner.py configs/jul.json min_distance
python runner.py configs/jul.json gs_state_aware_matching